import { type Request, type Response } from "express";
import { GoogleGenerativeAI } from "@google/generative-ai";

// Initialize Gemini API
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

interface ChatRequest {
    message: string;
    history: { role: "user" | "bot"; content: string }[];
    userName: string;
    userEmail: string;
}

export async function handleChat(req: Request, res: Response) {
    try {
        const { message, history, userName, userEmail } = req.body as ChatRequest;

        if (!process.env.GEMINI_API_KEY) {
            console.error("GEMINI_API_KEY is not set");
            return res.status(500).json({ error: "Chat service unavailable" });
        }

        // Construct the prompt with system instructions and history
        const systemInstruction = `
You are an executive assistant for KPI Digital. Your goal is to gather information from potential clients to understand their needs and how KPI Digital can help them.
KPI Digital helps trades businesses move from reactive chaos to predictable, profitable growth through Clarity (Business Intelligence), Systems (Automation), and Growth (Marketing & Sales).

Your instructions:
1. Be professional, concise, and helpful.
2. Ask relevant questions to understand the client's business, challenges, and goals.
3. Do not try to sell them immediately; focus on gathering information.
4. Once you have enough information (e.g., their business type, main challenge, and what they are looking for), you should trigger an email summary.
5. To trigger the email summary, your response MUST include a JSON block at the end in this format:
\`\`\`json
{
  "action": "send_email",
  "summary": "Client [Name] from [Business] is facing [Challenge]. They are interested in [Service]. Key details: [Details]."
}
\`\`\`
6. If you trigger the email, tell the user that you have sent their details to Louis and he will be in touch shortly.
7. Keep your responses short (under 3 sentences) unless explaining a complex concept.

Current User: ${userName} (${userEmail})
`;

        const chatHistory = history.map(msg => ({
            role: msg.role === "user" ? "user" : "model",
            parts: [{ text: msg.content }],
        }));

        const chat = model.startChat({
            history: [
                { role: "user", parts: [{ text: systemInstruction }] },
                { role: "model", parts: [{ text: "Understood. I am ready to act as the executive assistant for KPI Digital." }] },
                ...chatHistory
            ],
        });

        const result = await chat.sendMessage(message);
        const responseText = result.response.text();

        // Check for email trigger
        const jsonMatch = responseText.match(/```json\n([\s\S]*?)\n```/);
        let finalResponse = responseText;

        if (jsonMatch) {
            try {
                const actionData = JSON.parse(jsonMatch[1]);
                if (actionData.action === "send_email") {
                    // Send email to Louis
                    await sendSummaryEmail(actionData.summary, userName, userEmail);

                    // Remove the JSON block from the response sent to the user
                    finalResponse = responseText.replace(/```json\n[\s\S]*?\n```/, "").trim();
                }
            } catch (e) {
                console.error("Failed to parse action JSON:", e);
            }
        }

        res.json({ message: finalResponse });
    } catch (error) {
        console.error("Chat handler error:", error);
        res.status(500).json({ error: "Internal server error" });
    }
}

async function sendSummaryEmail(summary: string, userName: string, userEmail: string) {
    if (!process.env.RESEND_API_KEY) return;

    try {
        await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                from: 'KPI Digital Bot <noreply@receptionist.kpidigital.com.au>',
                to: ['louis@kpidigital.com.au'],
                subject: `Chat Summary - ${userName}`,
                html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #ea580c;">New Chat Summary</h2>
            <p><strong>Client:</strong> ${userName} (${userEmail})</p>
            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin-top: 0;">Summary</h3>
              <p>${summary}</p>
            </div>
            <p style="color: #666; font-size: 14px;">
              This summary was automatically generated by the AI chatbot.
            </p>
          </div>
        `,
            }),
        });
    } catch (error) {
        console.error("Failed to send summary email:", error);
    }
}
